development:
  adapter: mysql2
  database: app_dev
  host: localhost
  user: root
  pool: 5
  timeout: 5000

test:
  adapter: mysql2
  database: app_test
  host: localhost
  user: root
  pool: 5
  timeout: 5000
